spring:
  datasource:
    url: jdbc:h2:file:C:/data/ddic;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org.hibernate.SQL: debug

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true